### ISSUE TITLE
Change number of iterations in mbar

### ISSUE THREAD

**Issue by ncheron** [alchemistry/flamel#2] opened 2021-05-04 09:54 UTC
Hi,

I am using flamel to analyse FEP results (solvation free energy of acetate performed with Gromacs). With pymbar3.0.5 I encounter this issue https://github.com/choderalab/pymbar/issues/320. After switching to pymbar3.0.3, flamel works for switching off the charges, but not when I switch off van der waals (I still have the same issue). I have read here https://github.com/choderalab/pymbar/issues/419 a workaround (from Michael Shirts on March 22nd). Can you please guide me on where I should add these three lines in flamel to check if it works?

Thank you

Nicolas

PS : BTW, thank you for this tool, it is very useful

**Comment by orbeckst** [comment] 2021-05-04 19:18
@ncheron at the moment nobody is working on flamel so I am afraid, you're on your own figuring things out.

If you want to contribute code and work on it then you're more than welcome!!

**Comment by ncheron** [comment] 2021-05-11 12:00
Thank you for your answer. After switching from Gromacs2019.4 to Gromacs2021, my problems have disappeared and I don't know why. I will keep using Gromacs2021 for FEP.

**Comment by orbeckst** [comment] 2021-09-22 17:30
FYI, alchemlyb 0.5.1 fixed that (but not in flamel yet I think)

**Comment by schlaicha** [comment] 2021-09-23 10:18
I also just stumbled over that issue again - in flamel we just call the standard constructor of alchemlyb's MBAR introduced in alchemistry/alchemlyb#162 and changing the call in [flamel/estimator/mbar.py](https://github.com/alchemistry/flamel/blob/master/estimator/mbar.py#L30) to
```
mbar_est = alchemlyb.estimators.mbar_.MBAR(method="BFGS")
```
or
```
mbar_est = alchemlyb.estimators.mbar_.MBAR(method="adaptive")
```
both work fine in line with the discussion in [ choderalab/pymbar#419](https://github.com/choderalab/pymbar/issues/419#issuecomment-803714103). So the passing of the arguments in https://github.com/alchemistry/alchemlyb/pull/162 works as expected and the issue (at least for me) seems to be that in [alchemistry/alchemlyb](https://github.com/alchemistry/alchemlyb/blob/8c24a3a4d5e48627704623e42ee6dc6280fde492/src/alchemlyb/estimators/mbar_.py#L51) the default is `method='hybr'` which is not working for my particular system (roughly 1 out of 10 cases).

@orbeckst should I address this in [alchemistry/alchemlyb](https://github.com/alchemistry/alchemlyb)? If sticking to `method='hybr'` I suspect that the problem is that in [choderalab/pymbar](https://github.com/choderalab/pymbar/blob/master/pymbar/mbar_solvers.py) the `maxfev` for [scipy.optimize.root](https://docs.scipy.org/doc/scipy/reference/optimize.root-hybr.html) would need to be adjusted.

**Comment by orbeckst** [comment] 2021-09-23 16:17
Better discussed in alchemlyb — you can raise an issue to change the default setting of the MBAR estimator.

**Comment by orbeckst** [comment] 2022-11-06 23:25
@xiki-tempula is this issue addressed in the flamel rewrite, namely can one choose to use AutoMBAR for the ABFE workflow from the `flamel` command line?

**Comment by xiki-tempula** [comment] 2022-11-07 09:15
@orbeckst So for alchemlyb 1.0, using MBAR defaults to use AutoMBAR.
for alchemlyb 2.0 (https://github.com/alchemistry/alchemlyb/pull/268), The MBAR will defaults to use the `robust` method, which is the same as AutoMBAR.

Either way, we won't have this issue.

**Comment by orbeckst** [comment] 2022-11-07 16:35
Thanks for the clarification, I am closing the issue.

**Closed by orbeckst** 2022-11-07 16:35 UTC
Labels: enhancement
